driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: debian-7.4
    run_list:
      - recipe[apt]
  - name: fedora-19
  - name: fedora-20
  - name: freebsd-9.2
    run_list:
      - recipe[freebsd::portsnap]
  - name: freebsd-10.0 # unsupported until Chef 11.14.0
  - name: omnios-r151006j-r1
    driver:
      box: omnios-r151006j-r1
      box_url: http://omnios.omniti.com/media/OmniOS_r151008j-r1.box
    run_list:
      - recipe[ips-omniti]
  - name: ubuntu-10.04
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
 
suites:
  #
  # service55-single
  #
  - name: service55-single
    run_list:
    - recipe[mysql_service::single]
    includes: [
      'debian-7.0',
      'omnios-151006'
    ]
    attributes:
      mysql:
       version: '5.5'

  #
  # service55-multi
  #
  - name: service55-multi
    run_list:
    - recipe[mysql_service::multi]
    includes: [
      'debian-7.0',
      'omnios-151006'
    ]
    attributes:
      mysql:
       version: '5.5'
       port: '3308'
       data_dir: '/data/instance-2'
       run_user: 'bob'
       remove_anonymous_users: true
       remove_test_database: true
       root_acl: [ '127.0.0.1', 'mercury', 'venus', 'earth' ]
       root_password: 'never gonna make you cry'
       repl_acl: [ '127.0.0.1', '::1', 'localhost', 'mars', 'jupiter', 'saturn', 'uranus' ]
       repl_password: 'never gonna say goodbye'
       server_debian_password: 'never gonna tell a lie and hurt you'

  #
  # config
  #
  - name: config
    run_list:
    - recipe[mysql_config]

  #
  # replication-test
  #
  - name: replication-test
    run_list:
    - recipe[mysql_replication_test]